# Generated by Django 5.1.3 on 2024-12-05 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(help_text="닉네임", max_length=50, unique=True),
                ),
                (
                    "introduction",
                    models.CharField(
                        blank=True, help_text="소개", max_length=255, null=True
                    ),
                ),
                (
                    "avatar",
                    models.URLField(blank=True, help_text="프로필 이미지", null=True),
                ),
                (
                    "scopes",
                    models.CharField(
                        blank=True, help_text="권한들", max_length=255, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 프로필",
                "verbose_name_plural": "사용자 프로필들",
                "db_table": "user_profiles",
            },
        ),
    ]
