# Generated by Django 5.1.3 on 2024-12-08 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feeds", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(help_text="내용", max_length=500)),
                ("likes_count", models.IntegerField(default=0, help_text="좋아요 수")),
                (
                    "reported_count",
                    models.IntegerField(default=0, help_text="신고 횟수"),
                ),
                ("reply_count", models.IntegerField(default=0, help_text="답글 수")),
                (
                    "is_displayed",
                    models.BooleanField(default=True, help_text="표시 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feed",
                    models.ForeignKey(
                        help_text="피드",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="feeds.feed",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="부모 댓글",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comments.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "댓글",
                "verbose_name_plural": "댓글들",
                "db_table": "comments",
            },
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        help_text="댓글",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="comments.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "댓글 좋아요",
                "verbose_name_plural": "댓글 좋아요들",
                "db_table": "comment_likes",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "comment"), name="unique_user_comment_like"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CommentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(help_text="사유")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        help_text="댓글",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="comments.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "댓글 신고",
                "verbose_name_plural": "댓글 신고들",
                "db_table": "comment_reports",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "comment"), name="unique_user_comment_report"
                    )
                ],
            },
        ),
    ]
